CREATE TABLE EMPLOYEE
(
EID INT,
ENAME VARCHAR,
ADDRESS VARCHAR,
PHONENUMBER INT
);

SHOW TABLES;

INSERT INTO EMPLOYEE VALUES (100, 'Harish', 'Kondapur', 5551234);
SELECT * FROM EMPLOYEE;
DESC TABLE EMPLOYEE;
SHOW FILE FORMATS;

CREATE OR REPLACE FILE FORMAT CSVONE
TYPE = CSV
SKIP_HEADER=1
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n';

ALTER FILE FORMAT CSVONE
SET FIELD_OPTIONALLY_ENCLOSED_BY = '"'; --THIS IS WHEN WE HAVE COMMAS IN SINGLE COLUMN

ALTER FILE FORMAT CSVONE
SET ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE; 

ALTER FILE FORMAT CSVONE
SET DATE_FORMAT = 'DD-MM-YYYY';

DESC FILE FORMAT CSVONE;

CREATE OR REPLACE TABLE EMPLOAD(
Empid INT,
Name VARCHAR,
Email VARCHAR,
Phoneno	INT,
Address	VARCHAR,
COMPANY	VARCHAR,
EXP	INT,
"Joining Date" DATE
);

SELECT * FROM EMPLOAD;

CREATE OR REPLACE TABLE JSONDATA
(DATACOLUMN VARIANT);

CREATE OR REPLACE FILE FORMAT JSONTYPE
TYPE = JSON;

SELECT * FROM JSONDATA;

CREATE OR REPLACE TABLE XMLDATA
(DATACOLUMN VARIANT);

CREATE OR REPLACE FILE FORMAT XMLTYPE
TYPE = XML;

SELECT * FROM XMLDATA;

CREATE OR REPLACE TABLE PARQUETDATA
(DATACOLUMN VARIANT);

CREATE OR REPLACE FILE FORMAT PARQUETONE
TYPE = PARQUET;